### ISSUE TITLE
measuring intensity and frequency spectrum of the reflecting sound

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [steDamiano/pyroadacoustics#1]
my research requires calculating the intensity and frequency spectrum of the reflecting sound when a range of air pressures and sound frequencies are applied 

Could you tell me how I should use your package?
Thank you

**Comment by steDamiano** [comment]
Hi! 

Thanks for your question. The current version of the simulator does not provide separate outputs for the direct and reflected sound. Nonetheless, you can use a workaround to obtain it manually: the reflected sound is computed in the `simulatorManager.update()` method (line 332). If you manually add that value to the return method, then you can modify the `environment.simulate()` method at line 453 to read it, and use it for your analysis.

I hope this helps!
