### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by gillesmeyhi** [steDamiano/pyroadacoustics#2]
Hi,

The setup.py file mentions the following: `python_requires=">=3.7"`, however this should be changed to 3.9 or higher because otherwise you will get the  `TypeError: 'type' object is not subscriptable ` error which is caused by line 449 (`def _compute_delay(self, src_pos: np.ndarray, mic_pos: np.ndarray) -> tuple[float, float]:`) in simulatorManager.py because the tuple[T] syntax only works in Python 3.9 and up.

**Comment by steDamiano** [comment]
Solved in updated version
